### ISSUE TITLE
Document HTTP auth function usage in README

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/terraform-aws-s3-cloudfront-website#14]
From #4 :

@phuonghuynh Could you help add some documentation on the README (in new separate section) to describe how to use this? Thanks!

**Comment by mmeloni** [comment]
Hi all, I'm stuck on basic auth.
Terraform report following error when I plan:
```
Error: module "main": "bucket_name" is not a valid argument
Error: module "main": "basic_user" is not a valid argument
Error: module "main": "bucket_key" is not a valid argument
Error: module "main": "basic_password" is not a valid argument
```
Please can you explain better how to use this module?

**Comment by phuonghuynh** [comment]
@mmeloni you can check this sample https://github.com/riboseinc/terraform-aws-lambda-edge-authentication/tree/master/example

I will update Readme soon

**Comment by phuonghuynh** [comment]
@ronaldtse README updated with sample usage the lambda module; https://github.com/riboseinc/terraform-aws-s3-cloudfront-website/blob/master/README.adoc
