### ISSUE TITLE
Optional apex redirect via S3 bucket?

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/terraform-aws-s3-cloudfront-website#2]
We’d want to redirect e.g. "metanorma.com" to "www.metanorma.com", or vice-versa, to make websites more accessible.

I believe to achieve this we’ll have to add:

- an optional variable specifying the domain name that should be redirected to `fqdn`
- an additional `resource "aws_s3_bucket" "redirect"` (making use of the [redirect_all_requests_to](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html) option per [AWS docs](https://aws.amazon.com/blogs/aws/root-domain-website-hosting-for-amazon-s3/))
- the appropriate new Route 53 and CloudFront resources to make that bucket routable

I believe this should be optional (we don’t want this on subdomains such as open.ribose.com), but I’m not sure how to achieve that with HCL, so I’m leaving this up to someone more competent with HCL/Terraform to implement.

**Comment by ronaldtse** [comment]
Thanks @strogonoff , I've just done it in this new repo 😉 :

https://github.com/riboseinc/terraform-aws-s3-cloudfront-redirect

The https://metanorma.com site now redirects to https://www.metanorma.com !

**Comment by ronaldtse** [comment]
Maybe we'd like to add a note about this in this repo...

**Comment by ronaldtse** [comment]
Done!

**Comment by strogonoff** [comment]
@ronaldtse ah right, these are just TF modules and a concrete project can use one or both… I suppose I needed sleep when I wrote that comment, thanks for filling in :)

**Comment by ronaldtse** [comment]
Not at all, I’ve taken the chance to apply this change across all the Ribose Open sites, so we won’t have to worry about this anymore.
