### ISSUE TITLE
Enable IPv6 support

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/terraform-aws-s3-cloudfront-website#22]
From: https://github.com/riboseinc/rnpgp.com/issues/13

1. S3 bucket enable IPv6
2. Cloudfront enable IPv6
3. Determine best way to allow people to automatically enable IPv6 but ensuring them to create the necessary AAAA records...

@jackivanov would you be able to help here? Thanks!

**Comment by ronaldtse** [comment]
Relevant links:
* Route 53: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-cloudfront-distribution.html#routing-to-cloudfront-distribution-config
* Cloudfront: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesEnableIPv6
* S3: https://aws.amazon.com/blogs/aws/now-available-ipv6-support-for-amazon-s3/

**Comment by ronaldtse** [comment]
@jackivanov @phuonghuynh would you be able to help here? Thanks.

**Comment by jackivanov** [comment]
Hey @ronaldtse. OK, I'll take a look

**Comment by ronaldtse** [comment]
This is now fixed. Thanks @phuonghuynh !
