### ISSUE TITLE
Error: Provider configuration not present

### ISSUE THREAD

**Issue by joesoh** [riboseinc/terraform-aws-s3-cloudfront-website#25]
Hi, I get the above error when I run terraform plan with sample command from README. Hope you can assist.

My terraform version:  
terraform -v
Terraform v0.12.8
+ provider.AWS v2.29.0

Error Message:
<img width="625" alt="Screenshot 2019-09-25 at 22 42 14" src="https://user-images.githubusercontent.com/18061983/65611702-c65d0300-dfe5-11e9-81a5-157afcfe8584.png">

Error: Provider configuration not present

To work with module.main.aws_cloudfront_distribution.main-lambda-edge its
original provider configuration at module.main.provider.aws.cloudfront is
required, but it has been removed. This occurs when a provider configuration
is removed while objects created by that provider still exist in the state.
Re-add the provider configuration to destroy
module.main.aws_cloudfront_distribution.main-lambda-edge, after which you can
remove the provider configuration again.

**Comment by ronaldtse** [comment]
@joesoh thank you for the report! @phuonghuynh could you please help here? Thanks!

**Comment by ronaldtse** [comment]
@joesoh I believe this issue is fixed in c17aee4582a88105109ed51fcccf6c0ef783096d. Can you run `terraform init -upgrade` to try again? Thanks!

**Comment by abdennour** [comment]
Same issue as well ! 
![image](https://user-images.githubusercontent.com/1788384/89234507-cf026a80-d5f4-11ea-84d2-26f10803a008.png)
