### ISSUE TITLE
Upgrade to Terraform 0.15

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/terraform-aws-s3-cloudfront-website#33]

**Comment by ronaldtse** [comment]
@phuonghuynh is this now done? Thanks.

**Comment by phuonghuynh** [comment]
Yep, it's done. https://github.com/riboseinc/terraform-aws-s3-cloudfront-website/blob/master/versions.tf#L2

**Comment by ronaldtse** [comment]
Thanks @phuonghuynh !
