### ISSUE TITLE
`allowed_ips` is not allowed now

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/terraform-aws-s3-cloudfront-website#36]
@phuonghuynh the attribute `allowed_ips` is no longer allowed, we should remove that from the README.

**Comment by ronaldtse** [comment]
For @phuonghuynh . Thanks.

**Comment by phuonghuynh** [comment]
@ronaldtse "allowed_ips" is using in S3 to restrict IP-Sources accessibly. Should we remove this variable from the Terraform module?

**Comment by ronaldtse** [comment]
@phuonghuynh I thought it didn't work because there was a warning I received when using the module. If the variable is still accepted, let's keep it. Thanks.

**Comment by phuonghuynh** [comment]
So we keep variable "allowed_ips" as [comment](https://github.com/riboseinc/terraform-aws-s3-cloudfront-website/issues/36#issuecomment-878722881) to support restrict IP source accessibility.
