### ISSUE TITLE
Support for 4.x version of AWS Provider

### ISSUE THREAD

**Issue by girishadat** [riboseinc/terraform-aws-s3-cloudfront-website#38]
We have been getting errors from last week, as AWS Provider 4.0.0 got released. This is a major version change for the provider.

Currently, this module is not compatible with 4.x, so creating this issue (actually an enhancement) to add support for that latest release.

**Comment by girishadat** [comment]
PS: The errors I mentioned is when we do not have a version constraint to limit 4.x. There are no errors when we keep the constraint. Still, it is better to support the latest provider release.

**Comment by ronaldtse** [comment]
Thanks @girishadat for reporting the issue. I agree that compatibility is important. 

@phuonghuynh would you have time to prioritize this issue, and provide steps for existing users to upgrade the module? Thanks!

**Comment by phuonghuynh** [comment]
Yes

**Comment by phuonghuynh** [comment]
Ref link, discussion on dynamic block for "routing_rule" section, https://discuss.hashicorp.com/t/default-to-null-on-dynamic-blocks/13458/5
