### ISSUE TITLE
Name Tag is not overridable

### ISSUE THREAD

**Issue by vKongv** [riboseinc/terraform-aws-s3-cloudfront-website#39]
I have faced an issue where my CF `fqdn` name contains value (Eg: `*.website.com`) that are not allowed as a tag value in AWS: https://docs.aws.amazon.com/directoryservice/latest/devguide/API_Tag.html

Since S3's bucket name is not allowed to have "*" as part of the name, I have override the bucket name using `bucket_name` variable. But for the deployment, it will still use `fqdn` value as `Name` Tag value which causes me the following error

```
error updating S3 Bucket (abc.website.com) tags: error setting resource tags (abc.website.com): InvalidTag: The TagValue you have provided is invalid
```

There is a solution for this which is to use `local.localBucketName` as the `Name` Tag value rather than always hardcoded to `fqdn`. We can also allow overriding of tags value by switching the merge sequence.

**Comment by phuonghuynh** [comment]
Fixed in #40
