### ISSUE TITLE
Basic HTTP authentication module/function

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/terraform-aws-s3-cloudfront-website#4]
Add "basic HTTP authentication" to this module:

* a lambda function that authenticates against a file similar to `.htaccess` stored on the same bucket
* the `.htaccess` file can use the APR1 format (https://gist.github.com/samba/789122387e7f7330890b)
* the lambda function is used in Cloudfront for lambda@edge

**Comment by ronaldtse** [comment]
We can make a similar Lambda function to this:
* http://kynatro.com/blog/2018/01/03/a-step-by-step-guide-to-creating-a-password-protected-s3-bucket/

**Comment by ronaldtse** [comment]
@phuonghuynh any updates so far? Thanks!

**Comment by phuonghuynh** [comment]
@ronaldtse we protect `.htaccess` only or we define the file list somewhere?

**Comment by ronaldtse** [comment]
We need to define the list elsewhere, say a S3 json file.

**Comment by phuonghuynh** [comment]
@ronaldtse do you have any domain name that i could use to test ?

**Comment by ronaldtse** [comment]
@phuonghuynh do you still need a domain name to test?

**Comment by phuonghuynh** [comment]
Nope, i am using my own one.

**Comment by ronaldtse** [comment]
Cool, thanks!

**Comment by ronaldtse** [comment]
@phuonghuynh so this is fully complete in #12 . Could you help add some documentation on the README (in new separate section) to describe how to use this? Thanks!
