### ISSUE TITLE
Tag version for the last v3 and for the first v4

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/terraform-aws-s3-cloudfront-website#42]
@phuonghuynh can you also tag a version for the last v3 and for the first v4?

_Originally posted by @ronaldtse in https://github.com/riboseinc/terraform-aws-s3-cloudfront-website/issues/41#issuecomment-1086475098_

**Comment by phuonghuynh** [comment]
Last v3 tag: https://github.com/riboseinc/terraform-aws-s3-cloudfront-website/tree/v2.1.0
First v4 tag: https://github.com/riboseinc/terraform-aws-s3-cloudfront-website/tree/v3.0.0

**Comment by ronaldtse** [comment]
Thanks @phuonghuynh , can you update the README to show that as well? So people using different versions of Terraform can know what version of this module to use.
