### ISSUE TITLE
Issues after migrating to aws provider 4.0.0

### ISSUE THREAD

**Issue by girishadat** [riboseinc/terraform-aws-s3-cloudfront-website#43]
Hello,

We have used the updated module after the changes to use aws-provider version 4.x.

The module worked in some cases, but then we encountered an issue later. Not sure if the assumerole for the provider in the problematic case was causing some of the problems (at least the second one..?).

https://github.com/hashicorp/terraform-provider-aws/issues/13393#issuecomment-1126809777 - I had to use this workaround to get it working which finally allowed it to create buckets without errors like this `"Error: "origin.0.domain_name": required field is not set"`. So, https://github.com/riboseinc/terraform-aws-s3-cloudfront-website/blob/master/cloudfront.tf#L11 we changed like the below:

```
- domain_name = aws_s3_bucket.main.website_endpoint
+ domain_name = aws_s3_bucket_website_configuration.main.website_endpoint
```

Also, in s3.tf, all 4 resources needed the below line to get it working without errors.

`+ provider = aws.main`

Hope this helps you guys make improvements if you find them as needed changes/fixes.

**Comment by ronaldtse** [comment]
Thank you very much @girishadat !

@phuonghuynh could you please help update the module to support aws provider 4.0.0 and also provide details on how to migrate in the README? Thanks!

**Comment by phuonghuynh** [comment]
Yes, checking it

**Comment by phuonghuynh** [comment]
I will update Read Me for the migration steps; provider 4x supported already in https://github.com/riboseinc/terraform-aws-s3-cloudfront-website/releases/tag/v3.0.0

**Comment by ronaldtse** [comment]
Thanks @phuonghuynh , once README is updated please close this issue. Thanks!

**Comment by phuonghuynh** [comment]
Readme updated, https://github.com/riboseinc/terraform-aws-s3-cloudfront-website/commit/bd719deab079a33075a082b1bbb0079c0b3941c8
