### ISSUE TITLE
Support multiple aliases on the cloudfront distribution

### ISSUE THREAD

**Issue by colindean** [riboseinc/terraform-aws-s3-cloudfront-website#7]
I'm using a bare domain as the `fqdn` var. I've got a `aws_route53_record` that CNAMEs www to the bare, e.g.

```hcl
resource "aws_route53_record" "www" {
  provider = "aws.main"
  zone_id = "${data.aws_route53_zone.main.zone_id}"
  name = "www.${var.fqdn}"
  type = "CNAME"
  records = ["${var.fqdn}"]
  ttl = 300
}
```
Workaround for right now is to manually add the alias but that's so… 2010.

**Comment by colindean** [comment]
Looks like there needs to be a way to add more aliases that wind up present here: https://github.com/riboseinc/terraform-aws-s3-cloudfront-website/blob/bd2e36d4099d1c8aa102d058d021b1a4b5c722ca/cloudfront.tf#L51

**Comment by ronaldtse** [comment]
Thank you @colindean !
